### ISSUE TITLE
Overriding client contacts with database contacts on startup

### ISSUE THREAD

**Issue by delvh** [informatik-ag-ngl/envoy-client#129]
We need to overwrite the contacts of a client on login, as otherwise contacts can be lost (see below).
Because I once deleted the localdb of a User (who had another user as contact) and restored him, and now I do not have the other user as a contact anymore (empty contact list).
Another  question remains for this problem:
Does Hibernate automatically fetch the contacts of the user on login (when retrieving the user from the database)?

**Comment by CyB3RC0nN0R** [comment]
The problem is caused by the fact that the user list is in fact not directly representing the contacts received be the server, but rather the chats stores locally.
Everytime a contact is added, the client automatically create a chat for them. If this doesn't happen for some reason, the contact will not be visible to the user.
