### ISSUE TITLE
Voice Messages

### ISSUE THREAD

**Issue by delvh** [informatik-ag-ngl/envoy-client#33]
Sounds can be played when received.

**Comment by CyB3RC0nN0R** [comment]
So this means voice messages? I put together a checklist of stuff we need to implement to make this work:

- [ ] Recording microphone input

- [ ] Creating and sending a message to which that recording is attached

- [ ] Displaying that message inside the message list (playback button, timeline etc.)

- [ ] Playing the message back when the user presses the plyaback button in the message list

**Comment by CyB3RC0nN0R** [comment]
At the moment I am making quick progress on the issue. Recording voice, attaching it to a message and sending it off to the server already works. When receiving the messages, however, an error occurs, when a certain message size is exceeded. This is caused by the server not sending the entire message. The `Receiver` class has been hardened to log those errors instead of crashing completely.
